import { defineConfig } from 'cspell';

export default defineConfig({
  import: ['@sehv-oss/cspell-config', '@sehv-oss/cspell-config/pt-br'],
  ignorePaths: ['pnpm-lock.yaml', 'CHANGELOG.md'],
  words: [
    'aquí',
    'archivos',
    'añade',
    'dnd',
    'elegir',
    'fallido',
    'fieldsets',
    'figma',
    'fuster',
    'jetbrains',
    'jorgemolinafuster',
    'lanza',
    'lanzar',
    'límite',
    'molina',
    'nuevo',
    'presign',
    'progreso',
    'pudo',
    'sehv',
    'shiki',
    'sket',
    'sketchfile',
    'spanish',
    'subiendo',
    'suelta',
    'theming',
    'unstub',
    'uploaders',
  ],
});
